In [ ]:
import numpy as np
xnum = int(input('输入标准化后变量个数'))
conditionnum = int(input('输入约束条件个数'))
coefficient = input('输入标准化后目标函数各变量的系数').split(',')
coefficient = [float(x) for x in coefficient]
b = input('输入约束条件的值').split(',')
b = [float(x) for x in b]
c = [-1000,-1000,-1000]
def Base(conditionnum, xnum):#计算初始基
    base = []
    for basenum in range(conditionnum):
        base.append(xnum+1+basenum)
    return base
def CreateMartrix(conditionnum, b):#初始增广矩阵
    martrixlist = []
    for i in range(conditionnum):
        row = input('输入约束条件系数').split(',')
        row = [float(x) for x in row]
        row.append(b[i])
        martrixlist.append(row)
    martrix = np.array(martrixlist)
    return martrix
def TestNumLst(coefficient, c, martrix):#检验数计算
    testnumlst = []
    for m in range(len(coefficient)):
        lst = 0
        for n in range(len(c)):
            lst = lst + martrix[n, m] * c[n]
        testnum = coefficient[m] - lst
        testnumlst.append(testnum)
    return testnumlst
def TestNumJudge(testnumlst):#判断检验数
    for judge in testnumlst:
        if judge > 0:
            return False
def IntoBase(testnumlst):#找出入基变量索引
    testnumlst1 = testnumlst[:]
    for passnum in range(len(testnumlst)-1, 0, -1):
        for j in range(passnum):
            if testnumlst[j] > testnumlst[j+1]:
                testnumlst[j],testnumlst[j+1] = testnumlst[j+1],testnumlst[j]
    return testnumlst1.index(testnumlst[-1])
def SitaLst(b,martrix,intobase,base):#算出sita值
    dividendlst = martrix[:,intobase]
    sitalst = []
    for k in range(len(base)):
        if dividendlst[k] > 0:
            sita = b[k] / dividendlst[k]
        else:
            sita = 1000
        sitalst.append(sita)
    return sitalst
def SitaJudge(sitalst):#无界解检验
    ljl = 0
    for sitajudge in sitalst:
        if 0 < sitajudge and sitajudge < 1000:
            ljl = ljl+1
    if ljl==0:
        return False
    else:
        return True
def OutOfBase(sitalst, base):#找出出基变量索引
    sitalst1 = sitalst[:]
    for sitanum in range(len(sitalst)-1, 0, -1):
        for l in range(sitanum):
            if sitalst[l] > sitalst[l+1]:
                sitalst[l],sitalst[l+1] = sitalst[l+1],sitalst[l]
    outofsita = sitalst1.index(sitalst[0])
    outofbase = outofsita
    return outofbase
def MartrixChange(martrix, outofbase, intobase):#增广矩阵行变换
    k = 1 / martrix[outofbase, intobase]
    shape = martrix.shape
    martrix[outofbase,:] = martrix[outofbase,:]*k
    for rowchange in range(shape[0]):
        if rowchange != outofbase:
            k1 = martrix[rowchange, intobase]
            martrix[rowchange,:] = martrix[rowchange,:] - martrix[outofbase,:]*k1
            
        
    martrixchange = martrix
    return martrixchange

def Judge1(xnum,base):#无可行解检验
    for judgement1 in base:
        if judgement1 > xnum:
            return False
def Judge2(testnumlst,base):#无穷多最优解检验
    for judgement2 in base:
        testnumlst[judgement2-1] = -1
    for judgement3 in testnumlst:
        if judgement3 == 0:
            return False
martrix = CreateMartrix(conditionnum, b)#开始主程序
base = Base(conditionnum, xnum)
while True:
    
    testnumlst = TestNumLst(coefficient, c, martrix)#计算检验数
    print(testnumlst)
    if TestNumJudge(testnumlst)==False:        
        intobase = IntoBase(testnumlst)
        sitalst = SitaLst(b,martrix,intobase,base)
        if SitaJudge(sitalst) == False:
            print('无界解')
            break
        else:
            
            outofbase = OutOfBase(sitalst, base)
            print(outofbase)
           
            base[outofbase] = intobase + 1  #基更换
            print(base)
            martrix = MartrixChange(martrix, outofbase, intobase)
            print(martrix)
            c[outofbase] = coefficient[intobase]  #c更换
            print(c)
            b = list(martrix[:,-1])#b更换
            print('结束一次')
    else:
        if Judge1(xnum,base)==False:
            print(base)
            print('检验数小于零')
            print('无可行解')
            break
        else:
            if Judge2(testnumlst,base)==False:
                print('无穷多最优解')
                print(martrix[:,-1])
                print(base)
                break
            else:
                print(martrix[:,-1])
                print(base)
                break

In [1]:
b=[15,20,10]
conditionnum = 3
xnum=4
martrix = CreateMartrix(conditionnum, b)#开始主程序
base = Base(conditionnum, xnum)
print(martrix)
print(base)

NameError: name 'CreateMartrix' is not defined

In [6]:
c = [-1000,-1000,-1000]
coefficient=[1,2,3,-1]
testnumlst = TestNumLst(coefficient, c, martrix)
print(testnumlst)

[4001.0, 5002.0, 9003.0, 999.0]


In [7]:
print(TestNumJudge(testnumlst)==False)

True


In [8]:
intobase = IntoBase(testnumlst)
print(intobase)

2


In [9]:
base=[5,6,7]
sitalst = SitaLst(b,martrix,intobase,base)
print(sitalst)

[5.0, 4.0, 10.0]


In [10]:
print(SitaJudge(sitalst) == False)

False


In [11]:
outofbase = OutOfBase(sitalst, base)
print(outofbase)

1


In [12]:
base[outofbase] = intobase + 1  #基更换
print(base)

[5, 3, 7]


In [13]:
martrix = MartrixChange(martrix, outofbase, intobase)
print(martrix)

[[ -5.   -1.  -12.    0.  -45. ]
 [  0.4   0.2   1.    0.    4. ]
 [  0.6   1.8   0.    1.    6. ]]


In [22]:
martrix = np.array([[1,2,3,0,15],[2,1,5,0,20],[1,2,1,1,10]])
outofbase=1
intobase=2
def MartrixChange(martrix, outofbase, intobase):#增广矩阵行变换
    k = 1 / martrix[outofbase, intobase]
    shape = martrix.shape
    martrix[outofbase,:] = martrix[outofbase,:]*k
    for rowchange in range(shape[0]):
        if rowchange != outofbase:
            k1 = martrix[rowchange, intobase]
            martrix[rowchange,:] = martrix[rowchange,:] - martrix[outofbase,:]*k1
            
        
    martrixchange = martrix
    return martrixchange
martrix = MartrixChange(martrix, outofbase, intobase)
print(martrix)

[[1 2 0 0 3]
 [0 0 1 0 4]
 [1 2 0 1 6]]


In [4]:
c=[-1000,-1000,-1000]
outofbase=1
intobase=2
coefficient = input('输入标准化后目标函数各变量的系数').split(',')
coefficient = [float(x) for x in coefficient]
c[outofbase] = coefficient[intobase]
print(c)

输入标准化后目标函数各变量的系数1,2,3,-1
[-1000, 3.0, -1000]


In [5]:
conditionnum=5
base=[4,3,5]
print(Judge1(conditionnum,base)==False)

False
